# Generated by Django 5.2 on 2026-04-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('websocket', 'WebSocket en tiempo real')], default='websocket', max_length=12)),
            ],
            options={
                'verbose_name': 'Preferencia de notificación',
                'verbose_name_plural': 'Preferencias de notificación',
                'db_table': 'preferencias_notificacion',
            },
        ),
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('plantilla_titulo', models.CharField(max_length=200)),
                ('plantilla_cuerpo', models.TextField()),
            ],
            options={
                'verbose_name': 'Tipo de notificación',
                'verbose_name_plural': 'Tipos de notificación',
                'db_table': 'tipos_notificacion',
            },
        ),
    ]
