# Generated by Django 5.2 on 2026-05-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='totp_activo',
            field=models.BooleanField(default=False, help_text='True si el usuario tiene 2FA activado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='totp_secret',
            field=models.CharField(blank=True, default='', help_text='Secreto TOTP base32 para Google Authenticator', max_length=64),
        ),
    ]
