# Generated by Django 5.2 on 2026-05-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_agrega_2fa_totp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_url',
            field=models.URLField(blank=True, default='', help_text='URL Cloudinary de la foto de perfil (evita problemas con STORAGES)'),
        ),
    ]
