# Generated by Django 5.2 on 2026-06-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_agrega_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='whatsapp_activo',
            field=models.BooleanField(default=False, help_text='Si True, el usuario recibe notificaciones por WhatsApp en su teléfono registrado.'),
        ),
    ]
