# Generated by Django 5.2 on 2026-04-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApelacionMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Apelación de multa',
                'verbose_name_plural': 'Apelaciones de multa',
                'db_table': 'apelaciones_multa',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('apelada', 'En apelación'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10)),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='multas/evidencias/')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'db_table': 'multas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PagoMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr_pago', 'QR de pago')], max_length=15)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Pago de multa',
                'verbose_name_plural': 'Pagos de multa',
                'db_table': 'pagos_multa',
            },
        ),
        migrations.CreateModel(
            name='TipoMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Tipo de multa',
                'verbose_name_plural': 'Tipos de multa',
                'db_table': 'tipos_multa',
            },
        ),
    ]
