# Generated by Django 5.2 on 2026-04-24 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multas', '0001_initial'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apelacionmulta',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apelaciones_resueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apelacionmulta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apelaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multa',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multa',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='apelacionmulta',
            name='multa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apelacion', to='multas.multa'),
        ),
        migrations.AddField(
            model_name='pagomulta',
            name='multa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='multas.multa'),
        ),
        migrations.AddField(
            model_name='pagomulta',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_multa_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='multas.tipomulta'),
        ),
    ]
