# Generated by Django 5.2 on 2026-05-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomulta',
            name='comprobante_url',
            field=models.URLField(blank=True, default='', help_text='URL Cloudinary del comprobante/screenshot de pago digital'),
        ),
        migrations.AddField(
            model_name='pagomulta',
            name='referencia_pago',
            field=models.CharField(blank=True, default='', help_text='Número de referencia o código de transacción bancaria', max_length=60),
        ),
        migrations.AlterField(
            model_name='multa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'Comprobante en revisión'), ('pagada', 'Pagada'), ('apelada', 'En apelación'), ('cancelada', 'Cancelada')], default='pendiente', max_length=12),
        ),
        migrations.AlterField(
            model_name='pagomulta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo (ventanilla)'), ('transferencia', 'Transferencia bancaria'), ('qr_pago', 'QR de Pago'), ('banca_movil', 'Banca Móvil / Tigo Money')], max_length=15),
        ),
    ]
