# Generated by Django 5.2 on 2026-04-24 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('es_discapacidad', models.BooleanField(default=False)),
                ('color', models.CharField(default='#3B82F6', help_text='Color hex para mapa visual', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoría de espacio',
                'verbose_name_plural': 'Categorías de espacios',
                'db_table': 'categorias_espacios',
            },
        ),
        migrations.CreateModel(
            name='PagoSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr_pago', 'QR de pago')], max_length=15)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Pago de sesión',
                'verbose_name_plural': 'Pagos de sesión',
                'db_table': 'pagos_sesion',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='pendiente', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SesionParqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('total_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='activa', max_length=10)),
            ],
            options={
                'verbose_name': 'Sesión de parqueo',
                'verbose_name_plural': 'Sesiones de parqueo',
                'db_table': 'sesiones_parqueo',
                'ordering': ['-hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'tarifas',
            },
        ),
        migrations.CreateModel(
            name='ZonaParqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('capacidad_total', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona de parqueo',
                'verbose_name_plural': 'Zonas de parqueo',
                'db_table': 'zonas_parqueo',
            },
        ),
        migrations.CreateModel(
            name='EspacioParqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado'), ('mantenimiento', 'En mantenimiento')], default='disponible', max_length=15)),
                ('ubicacion_referencia', models.CharField(blank=True, max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='espacios', to='parqueos.categoriaespacio')),
            ],
            options={
                'verbose_name': 'Espacio de parqueo',
                'verbose_name_plural': 'Espacios de parqueo',
                'db_table': 'espacios_parqueo',
            },
        ),
    ]
