# Generated by Django 5.2 on 2026-04-24 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueos', '0001_initial'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosesion',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_sesion_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='parqueos.espacioparqueo'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='sesionparqueo',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='parqueos.espacioparqueo'),
        ),
        migrations.AddField(
            model_name='sesionparqueo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_parqueo', to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='pagosesion',
            name='sesion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='parqueos.sesionparqueo'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='parqueos.categoriaespacio'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='tipo_vehiculo',
            field=models.ForeignKey(blank=True, help_text='Nulo = aplica a todos los tipos', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='vehiculos.tipovehiculo'),
        ),
        migrations.AddField(
            model_name='sesionparqueo',
            name='tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parqueos.tarifa'),
        ),
        migrations.AddField(
            model_name='espacioparqueo',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='parqueos.zonaparqueo'),
        ),
        migrations.AlterUniqueTogether(
            name='espacioparqueo',
            unique_together={('zona', 'numero')},
        ),
    ]
