# Generated by Django 5.2 on 2026-04-25 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='tipo_vehiculo',
        ),
        migrations.RemoveField(
            model_name='sesionparqueo',
            name='tarifa',
        ),
        migrations.RemoveField(
            model_name='sesionparqueo',
            name='total_cobrado',
        ),
        migrations.DeleteModel(
            name='PagoSesion',
        ),
        migrations.DeleteModel(
            name='Tarifa',
        ),
    ]
