# Generated by Django 5.2 on 2026-06-11 02:58

import django.utils.timezone
from django.db import migrations, models


def _cerrar_sesiones_activas_duplicadas(apps, schema_editor):
    """
    Antes de crear los constraints únicos parciales, cierra duplicados
    preexistentes (si los hubiera): conserva la sesión activa más reciente
    por vehículo y por espacio, cierra el resto. Sin esto, una sola fila
    duplicada en producción haría fallar el deploy completo.
    """
    SesionParqueo = apps.get_model("parqueos", "SesionParqueo")
    for campo in ("vehiculo_id", "espacio_id"):
        vistos = set()
        for sesion in SesionParqueo.objects.filter(estado="activa").order_by("-hora_entrada"):
            clave = getattr(sesion, campo)
            if clave in vistos:
                sesion.estado = "cerrada"
                sesion.hora_salida = sesion.hora_salida or django.utils.timezone.now()
                sesion.save(update_fields=["estado", "hora_salida"])
            else:
                vistos.add(clave)


class Migration(migrations.Migration):

    dependencies = [
        ('parqueos', '0003_remove_tarifa_categoria_remove_tarifa_tipo_vehiculo_and_more'),
        ('vehiculos', '0009_alter_vehiculoestadohistorial_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='vehiculo',
        ),
        migrations.AlterField(
            model_name='sesionparqueo',
            name='hora_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(
            _cerrar_sesiones_activas_duplicadas,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='sesionparqueo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('vehiculo',), name='unica_sesion_activa_por_vehiculo'),
        ),
        migrations.AddConstraint(
            model_name='sesionparqueo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('espacio',), name='unica_sesion_activa_por_espacio'),
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
