# Generated by Django 5.2 on 2026-06-13 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0015_rename_alertas_acc_revisada_idx_alertas_acc_revisad_c1cb2a_idx_and_more'),
        ('parqueos', '0004_remove_reserva_espacio_remove_reserva_vehiculo_and_more'),
        ('vehiculos', '0010_canonicalizar_placas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionparqueo',
            name='vehiculo_temporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_parqueo', to='acceso.vehiculotemporal'),
        ),
        migrations.AlterField(
            model_name='sesionparqueo',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_parqueo', to='vehiculos.vehiculo'),
        ),
    ]
