# Generated by Django 5.2 on 2026-04-24 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_vehiculo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de visita',
                'verbose_name_plural': 'Tipos de visita',
                'db_table': 'tipos_visita',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de identidad')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='visitantes/fotos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitantes',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=12)),
                ('fecha_entrada', models.DateTimeField(blank=True, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anfitrion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas_como_anfitrion', to=settings.AUTH_USER_MODEL)),
                ('tipo_visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='visitantes.tipovisita')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='vehiculos.vehiculo')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='visitantes.visitante')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'db_table': 'visitas',
                'ordering': ['-created_at'],
            },
        ),
    ]
