# Generated by Django 5.2 on 2026-05-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='placa_vehiculo_visitante',
            field=models.CharField(blank=True, default='', help_text='Placa, TAXI, BUS o vacío si vino a pie. Solo para vehículos externos.', max_length=20),
        ),
    ]
