# Generated by Django 5.2 on 2026-06-14 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0017_registroacceso_imagen_url'),
        ('visitantes', '0007_visitante_datos_previos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependenciauagrm',
            options={'ordering': ['nombre'], 'verbose_name': 'Dependencia UAGRM', 'verbose_name_plural': 'Dependencias UAGRM'},
        ),
        migrations.AddField(
            model_name='visita',
            name='vehiculo_temporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='acceso.vehiculotemporal'),
        ),
        migrations.AlterField(
            model_name='dependenciauagrm',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='dependenciauagrm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dependenciauagrm',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='tipovisita',
            name='duracion_esperada_horas',
            field=models.PositiveSmallIntegerField(default=4, help_text='Umbral en horas. Pasado este tiempo se notifica al anfitrión y se auto-cierra si no hay respuesta.'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='dependencia',
            field=models.ForeignKey(blank=True, help_text='Destino institucional cuando no hay anfitrión específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='visitantes.dependenciauagrm'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='notificacion_anfitrion_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visita',
            name='num_acompanantes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Personas adicionales que ingresan con el visitante.'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='tipo_cierre',
            field=models.CharField(blank=True, choices=[('manual_guardia', 'Registrada por guardia'), ('confirmado_anfitrion', 'Confirmada por anfitrión'), ('auto', 'Auto-cerrada — salida no verificada')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='destino_sugerido_texto',
            field=models.CharField(blank=True, default='', help_text='Destino indicado por el visitante al pre-registrarse (texto libre).', max_length=120),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='placa_habitual',
            field=models.CharField(blank=True, default='', help_text='Placa del vehículo con el que suele venir (pre-llenada en /register).', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='procedencia',
            field=models.CharField(blank=True, default='', help_text='Ciudad, empresa o institución de procedencia.', max_length=120),
        ),
    ]
