# Generated by Django 5.2 on 2026-04-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaseTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('valido_desde', models.DateTimeField()),
                ('valido_hasta', models.DateTimeField()),
                ('usos_max', models.PositiveSmallIntegerField(default=1)),
                ('usos_actual', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pase temporal',
                'verbose_name_plural': 'Pases temporales',
                'db_table': 'pases_temporales',
            },
        ),
        migrations.CreateModel(
            name='PuntoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ambos', 'Entrada y Salida')], default='ambos', max_length=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Punto de acceso',
                'verbose_name_plural': 'Puntos de acceso',
                'db_table': 'puntos_acceso',
            },
        ),
        migrations.CreateModel(
            name='QrSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_qr', models.ImageField(blank=True, null=True, upload_to='acceso/qr/')),
                ('codigo_hash', models.CharField(max_length=64, unique=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'QR de sesión',
                'verbose_name_plural': 'QR de sesiones',
                'db_table': 'qr_sesiones',
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Registros de acceso',
                'db_table': 'registros_acceso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
