# Generated by Django 5.2 on 2026-04-24 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceso', '0001_initial'),
        ('parqueos', '0001_initial'),
        ('vehiculos', '0001_initial'),
        ('visitantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pasetemporal',
            name='generado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pases_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pasetemporal',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pases_temporales', to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='pasetemporal',
            name='visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pases_temporales', to='visitantes.visitante'),
        ),
        migrations.AddField(
            model_name='qrsesion',
            name='sesion_parqueo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_sesiones', to='parqueos.sesionparqueo'),
        ),
        migrations.AddField(
            model_name='qrsesion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sesiones', to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='pase_temporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='acceso.pasetemporal'),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='punto_acceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='acceso.puntoacceso'),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='qr_sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='acceso.qrsesion'),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_acceso_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_acceso', to='vehiculos.vehiculo'),
        ),
        migrations.AddIndex(
            model_name='qrsesion',
            index=models.Index(fields=['codigo_hash'], name='qr_sesiones_codigo__c7a0cd_idx'),
        ),
    ]
