# Generated by Django 5.2 on 2026-04-25 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_initial'),
        ('vehiculos', '0002_vehiculo_codigo_qr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrsesion',
            options={'verbose_name': 'QR de delegación', 'verbose_name_plural': 'QR de delegaciones'},
        ),
        migrations.RenameField(
            model_name='registroacceso',
            old_name='qr_sesion',
            new_name='qr_delegacion',
        ),
        migrations.RenameIndex(
            model_name='qrsesion',
            new_name='qr_delegaci_codigo__785091_idx',
            old_name='qr_sesiones_codigo__c7a0cd_idx',
        ),
        migrations.RemoveField(
            model_name='qrsesion',
            name='imagen_qr',
        ),
        migrations.RemoveField(
            model_name='qrsesion',
            name='sesion_parqueo',
        ),
        migrations.AddField(
            model_name='qrsesion',
            name='generado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_delegaciones_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrsesion',
            name='motivo',
            field=models.CharField(blank=True, help_text='Razón de la delegación (préstamo a familiar, autorización especial, etc.)', max_length=150),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='metodo_acceso',
            field=models.CharField(choices=[('qr_permanente', 'QR permanente del vehículo'), ('qr_delegacion', 'QR de delegación'), ('pase_temporal', 'Pase temporal'), ('manual', 'Ingreso manual por guardia')], default='qr_permanente', max_length=15),
        ),
        migrations.AlterField(
            model_name='qrsesion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_delegaciones', to='vehiculos.vehiculo'),
        ),
        migrations.AlterModelTable(
            name='qrsesion',
            table='qr_delegaciones',
        ),
    ]
