# Generated by Django 5.2 on 2026-06-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0014_qrsesion_destinatario'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertaacceso',
            new_name='alertas_acc_revisad_c1cb2a_idx',
            old_name='alertas_acc_revisada_idx',
        ),
        migrations.AlterField(
            model_name='alertaacceso',
            name='tipo_anomalia',
            field=models.CharField(choices=[('frecuencia_excesiva', 'Frecuencia excesiva de accesos'), ('horario_inusual', 'Acceso fuera de horario habitual'), ('punto_inusual', 'Punto de acceso inusual'), ('vehiculo_sancionado', 'Vehículo sancionado con acceso reciente'), ('placas_similares', 'Placas similares (posible clonación)'), ('documento_vencido', 'Documento vencido (SOAT, técnica, circulación)')], max_length=25),
        ),
        migrations.AlterField(
            model_name='autorizacionaccesoexterno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='metodo_acceso',
            field=models.CharField(choices=[('qr_dinamico', 'QR dinámico TOTP (seguro, caduca cada 30s)'), ('qr_permanente', 'QR permanente del vehículo (legacy)'), ('qr_delegacion', 'QR de delegación'), ('pase_temporal', 'Pase temporal'), ('temporal', 'Acceso temporal de proveedor/externo'), ('manual', 'Ingreso manual por guardia')], default='qr_dinamico', max_length=15),
        ),
        migrations.AlterField(
            model_name='ubicacionvehiculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
