# Generated by Django 5.2 on 2026-06-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0015_rename_alertas_acc_revisada_idx_alertas_acc_revisad_c1cb2a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaacceso',
            name='tipo_anomalia',
            field=models.CharField(choices=[('frecuencia_excesiva', 'Frecuencia excesiva de accesos'), ('horario_inusual', 'Acceso fuera de horario habitual'), ('punto_inusual', 'Punto de acceso inusual'), ('vehiculo_sancionado', 'Vehículo sancionado con acceso reciente'), ('placas_similares', 'Placas similares (posible clonación)'), ('documento_vencido', 'Documento vencido (SOAT, técnica, circulación)'), ('vehiculo_en_alerta', 'Vehículo en alerta de seguridad (robo/búsqueda)')], max_length=25),
        ),
    ]
