# Generated by Django 5.2 on 2026-06-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0016_alter_alertaacceso_tipo_anomalia'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacceso',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
    ]
