# Generated by Django 5.2 on 2026-06-15 23:21

from django.db import migrations, models


def _migrar_usos(apps, schema_editor):
    """
    Filas existentes eran de un solo uso (booleano `usado`). Al pasar al modelo
    entrada+salida (usos_max=2), una autorización ya marcada `usado=True` se
    considera totalmente consumida (usos_actual = usos_max). Las no usadas
    quedan en 0 (el default), listas para entrada+salida.
    """
    Auth = apps.get_model('acceso', 'AutorizacionAccesoExterno')
    Auth.objects.filter(usado=True).update(usos_actual=2)


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0017_registroacceso_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionaccesoexterno',
            name='usos_actual',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autorizacionaccesoexterno',
            name='usos_max',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.RunPython(_migrar_usos, migrations.RunPython.noop),
    ]
