# Generated by Django 5.2 on 2026-04-24 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de vehículo',
                'verbose_name_plural': 'Tipos de vehículo',
                'db_table': 'tipos_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('anio', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=40)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('sancionado', 'Sancionado')], default='activo', max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/fotos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='vehiculos.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='HistorialPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_vehiculos', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_propietarios', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Historial de propietario',
                'verbose_name_plural': 'Historial de propietarios',
                'db_table': 'historial_propietarios',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('soat', 'SOAT'), ('tecnica', 'Revisión técnica'), ('circulacion', 'Permiso de circulación'), ('otro', 'Otro')], max_length=15)),
                ('numero', models.CharField(max_length=60)),
                ('fecha_vencimiento', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='vehiculos/documentos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Documento de vehículo',
                'verbose_name_plural': 'Documentos de vehículo',
                'db_table': 'documentos_vehiculo',
            },
        ),
    ]
