# Generated by Django 5.2 on 2026-04-25 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='codigo_qr',
            field=models.CharField(blank=True, help_text='Hash SHA-256 generado al registrar el vehículo. Funciona mientras estado=activo.', max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['codigo_qr'], name='vehiculos_codigo__ec5105_idx'),
        ),
    ]
