# Generated by Django 5.2 on 2026-05-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculo_codigo_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('sancionado', 'Sancionado')], default='pendiente', max_length=15),
        ),
    ]
