# Generated by Django 5.2 on 2026-05-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculo_qr_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='codigo_qr',
            field=models.CharField(blank=True, help_text='Hash SHA-256 estático (legacy). Se mantiene para compatibilidad con QrSesion.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='qr_secret',
            field=models.CharField(blank=True, help_text='Clave secreta para QR dinámico TOTP. NUNCA se expone al cliente directamente.', max_length=64),
        ),
    ]
