# Generated by Django 5.2 on 2026-06-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_vehiculo_estado_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculoestadohistorial',
            name='fecha',
            field=models.DateTimeField(default=None),
        ),
    ]
