# Generated by Django 5.2 on 2026-06-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0011_placas_formato_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='en_alerta',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='motivo_alerta',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
