# Generated by Django 5.2 on 2026-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0012_vehiculo_en_alerta_vehiculo_motivo_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='es_frecuente',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
